src/config/routes.rb
Rails.application.routes.draw do
  get 'buyer/page'
  resources :listings
  resources :categories
  resources :profiles
  devise_for :users
  root 'home#page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

src/app/models/listing.rb
class Listing < ApplicationRecord
  #Each listing has many categories
  belongs_to :category
  # belongs_to :profile. Checks optional for a buyer, as some users will not buy an item. WIll only update if they do purchase an item. Attached only one image to a listing.
  belongs_to :buyer, class_name: "Profile", optional: true
  belongs_to :seller, class_name: "Profile"
  has_one_attached :picture
end

src/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
    if params[:category]
      @listings = Listing.where(category_id: params[:category].to_i)
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
    #Verification passed here so that only the current user can edit a post if id's match.
    if current_user.profile.id!=@listing.profile_id
      redirect_to listings_path
    end
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    @listing.profile_id = current_user.profile.id
    @listing.seller_id = current_user.profile.id



    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      #Updated params with required list of my added items.
      params.require(:listing).permit(:item_name, :category_id, :description, :price, :seller_id, :buyer_id, :profile_id, :picture)
    end
end

src/app/helpers/listings_helper.rb
module ListingsHelper
end

src/app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  <br>
    <%= f.input :item_name %>
  <br>
    <%= f.association :category %>
  <br>
    <%= f.input :description %>
  <br>
    <%= f.input :price %>
  <br>
    <%= f.file_field :picture %>
  <br>
  </div>
  <br>

  <div class="form-actions">
  <br>
    <%= f.button :submit %>
  </div>
<% end %>

src/app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

src/app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<div class="row">
 <% @listings.each do |listing| %>
<div class= "col-md-3">
  <div class="card" style="width: 18rem;">
    <%=image_tag listing.picture, class: "card-img-top" %>

  <div class="card-body">
    <h5 class="card-title">  <%= listing.item_name %></h5>
        <%= number_to_currency(listing.price) %>
    <p class="card-text">  <%= listing.description %>.</p>
    <%= link_to 'Show', listing, class: "btn btn-primary" %>

  </div>
</div>
</div>
<% end %>
</div>

src/app/views/listings/new.html.erb
<div class="jumbotron">
  <div class="container">

    <h1 class="display-4">New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

  </div>
  </div>
</div>

src/app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @listing.picture if @listing.picture.attached? %>

<p>
  <strong>Item name:</strong>
  <%= @listing.item_name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @listing.category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@listing.price) %>
</p>

<%# Added Verification for editting listings %>
<%= link_to 'Edit', edit_listing_path(@listing) if current_user.profile.id==@listing.profile_id %> |
<%= link_to 'Back', listings_path %>
<div>
</div>
<div>
</div>
<div class="btn-group mr-2" role="group" aria-label="First group">
<%= link_to "Buy", buyer_page_path(listing: @listing.id), class: "btn btn-secondary" %>
</div>