src/config/routes.rb
Rails.application.routes.draw do
  get 'buyer/page'
  resources :listings
  resources :categories
  resources :profiles
  devise_for :users
  root 'home#page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

src/app/views/partials/_navbar.html.erb
<%# Created a sticky nav bar with access to all of the website. Home, back, create a listing,  %>
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
<div class="col-md-3">
  <a class="navbar-brand" href="/">RocketLeet</a>  
    <%= link_to 'Back', root_path, class: "nav-item btn btn-primary"  %>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
</div>
<div class="col-md-7">
    <%= link_to 'Sell My Item', new_listing_path, class: "nav-item btn btn-primary"  %>
    <% if current_user%>
    <% if Profile.find_by(user_id: current_user.id)%>
    <%= link_to 'View My Profile', profile_path(Profile.find_by(user_id: current_user.id).id), class: "nav- btn btn-primary" %>
    <%= link_to 'View All Listings', listings_path, class: "nav- btn btn-primary" %>
    <% end %>
    <% end %>
    


</div>
<%# Added logout function to destroy user session. %>
  <div class="col-md-2 nav-right">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
       <li class="nav-item active"> 
        <% if user_signed_in? %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% end %>
       </li>
      </ul>
    </div>
    <div>
    </div>
    <div>
</div>
  </div>
</nav>